apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: apps
    # repoURL: 'https://github.com/morey-tech/argo-cd-app-of-apps-demo'
    repoURL: 'https://github.com/github2020-g/argocd-tutorial/tree/main/03-appOfApps'
    targetRevision: HEAD
  project: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
